// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },

  // IMPORTANT: use DIRECT connection for migrations (port 5432), not the pooler.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
